// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: backup_document_file.proto

package internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// A file in Android's DocumentsProvider.
//
// Excluded for now, but maybe interesting for later:
//   - DocumentsContract.Document.COLUMN_MIME_TYPE
//   - DocumentsContract.Document.COLUMN_SUMMARY
type BackupDocumentFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path         string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	LastModified int64  `protobuf:"varint,3,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	Size         int64  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// *
	// This is empty for MediaStore.VOLUME_EXTERNAL_PRIMARY or "primary"
	Volume string `protobuf:"bytes,5,opt,name=volume,proto3" json:"volume,omitempty"`
	// *
	// An ordered list of chunk IDs whose chunks that make up the file's content.
	ChunkIds []string `protobuf:"bytes,6,rep,name=chunk_ids,json=chunkIds,proto3" json:"chunk_ids,omitempty"`
	// *
	// If there is a single chunk ID and this is not 0, then the chunk ID refers to a zip chunk
	// and this file can be found at the zip entry with this index name.
	ZipIndex int32 `protobuf:"varint,7,opt,name=zip_index,json=zipIndex,proto3" json:"zip_index,omitempty"`
}

func (x *BackupDocumentFile) Reset() {
	*x = BackupDocumentFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backup_document_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupDocumentFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupDocumentFile) ProtoMessage() {}

func (x *BackupDocumentFile) ProtoReflect() protoreflect.Message {
	mi := &file_backup_document_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupDocumentFile.ProtoReflect.Descriptor instead.
func (*BackupDocumentFile) Descriptor() ([]byte, []int) {
	return file_backup_document_file_proto_rawDescGZIP(), []int{0}
}

func (x *BackupDocumentFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupDocumentFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BackupDocumentFile) GetLastModified() int64 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

func (x *BackupDocumentFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BackupDocumentFile) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *BackupDocumentFile) GetChunkIds() []string {
	if x != nil {
		return x.ChunkIds
	}
	return nil
}

func (x *BackupDocumentFile) GetZipIndex() int32 {
	if x != nil {
		return x.ZipIndex
	}
	return 0
}

var File_backup_document_file_proto protoreflect.FileDescriptor

var file_backup_document_file_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x21, 0x6f, 0x72,
	0x67, 0x2e, 0x63, 0x61, 0x6c, 0x79, 0x78, 0x6f, 0x73, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x22,
	0xc7, 0x01, 0x0a, 0x12, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x23,
	0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x64, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x7a, 0x69, 0x70, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x7a, 0x69, 0x70, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x42, 0x05, 0x50, 0x01, 0x5a, 0x01, 0x2e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_backup_document_file_proto_rawDescOnce sync.Once
	file_backup_document_file_proto_rawDescData = file_backup_document_file_proto_rawDesc
)

func file_backup_document_file_proto_rawDescGZIP() []byte {
	file_backup_document_file_proto_rawDescOnce.Do(func() {
		file_backup_document_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_backup_document_file_proto_rawDescData)
	})
	return file_backup_document_file_proto_rawDescData
}

var file_backup_document_file_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_backup_document_file_proto_goTypes = []interface{}{
	(*BackupDocumentFile)(nil), // 0: org.calyxos.backup.storage.backup.BackupDocumentFile
}
var file_backup_document_file_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_backup_document_file_proto_init() }
func file_backup_document_file_proto_init() {
	if File_backup_document_file_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_backup_document_file_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupDocumentFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backup_document_file_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backup_document_file_proto_goTypes,
		DependencyIndexes: file_backup_document_file_proto_depIdxs,
		MessageInfos:      file_backup_document_file_proto_msgTypes,
	}.Build()
	File_backup_document_file_proto = out.File
	file_backup_document_file_proto_rawDesc = nil
	file_backup_document_file_proto_goTypes = nil
	file_backup_document_file_proto_depIdxs = nil
}
